export interface Product {
  id: string
  name: string
  slug: string
  price: number
  compareAtPrice?: number
  description: string
  category: string
  tags: string[]
  images: string[]
  rating: number
  reviewCount: number
  inStock: boolean
  featured: boolean
}

const products: Product[] = [
  {
    id: "pet-001",
    name: "HydroPaws Portable Pet Water Bottle",
    slug: "hydropaws-portable-pet-water-bottle",
    price: 24.99,
    compareAtPrice: 34.99,
    description: "3-in-1 portable water bottle with built-in bowl and treat compartment. Leak-proof design with one-hand operation. Perfect for walks, hikes, and travel. BPA-free materials hold 500ml of water. No more thirsty pups on the go!",
    category: "Travel & Outdoors",
    tags: ["dog", "water", "travel", "portable", "bottle", "hiking"],
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    rating: 4.7,
    reviewCount: 3452,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-002",
    name: "FurEase 2-in-1 Grooming Mist Brush",
    slug: "furease-2-in-1-grooming-mist-brush",
    price: 29.99,
    compareAtPrice: 39.99,
    description: "Revolutionary grooming brush with built-in water spray. Detangles, reduces shedding, and conditions in one step. Fill with water or pet-safe conditioner. Self-cleaning mechanism — retracts bristles with one click. 424+ sales/month proven.",
    category: "Grooming Tools",
    tags: ["dog", "cat", "grooming", "brush", "mist", "shedding"],
    images: [
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.6,
    reviewCount: 2891,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-003",
    name: "CalmLick Slow Feeder Lick Mat",
    slug: "calmlick-slow-feeder-lick-mat",
    price: 16.99,
    compareAtPrice: 22.99,
    description: "Silicone lick mat with raised ridges that promotes slow eating and reduces anxiety. Spread peanut butter, yogurt, or wet food for 30+ minutes of entertainment. Suction cups stick to walls or floors. Dishwasher safe. Trending #1 on TikTok.",
    category: "Feeding",
    tags: ["dog", "cat", "slow feeder", "lick mat", "anxiety", "enrichment"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    rating: 4.8,
    reviewCount: 5678,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-004",
    name: "PawRelax Donut Pet Bed",
    slug: "pawrelax-donut-pet-bed",
    price: 44.99,
    compareAtPrice: 59.99,
    description: "Ultra-soft donut-shaped bed with raised rim for security and warmth. High-loft microfiber filling keeps shape. Non-slip bottom. Machine washable cover. Anxiety-reducing design — pets feel like they're being hugged. 4 sizes available.",
    category: "Beds & Furniture",
    tags: ["dog", "cat", "bed", "donut", "anxiety", "comfort"],
    images: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
    ],
    rating: 4.7,
    reviewCount: 4321,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-005",
    name: "Pet Hair Removal Gloves (Pair)",
    slug: "pet-hair-removal-gloves-pair",
    price: 14.99,
    compareAtPrice: 19.99,
    description: "Silicone grooming gloves that remove loose hair while petting your dog or cat. 360° rubber tips grab hair from all coat types. Works wet or dry. Collects hair in easy-to-remove clumps. Massages skin and improves circulation. Over 10K+ monthly sales.",
    category: "Grooming Tools",
    tags: ["dog", "cat", "grooming", "gloves", "shedding", "hair removal"],
    images: [
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.5,
    reviewCount: 8901,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-006",
    name: "Adjustable No-Pull Dog Harness",
    slug: "adjustable-no-pull-dog-harness",
    price: 32.99,
    compareAtPrice: 44.99,
    description: "Ergonomic no-pull harness with padded chest plate and 2 D-rings. Front clip stops pulling — back clip for casual walks. Reflective stitching for night safety. Quick-release buckles. 4 adjustment points for perfect fit. Sizes XS-XL.",
    category: "Collars & Leashes",
    tags: ["dog", "harness", "no-pull", "walking", "reflective", "safety"],
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.6,
    reviewCount: 6543,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-007",
    name: "Self-Cleaning Deshedding Brush",
    slug: "self-cleaning-deshedding-brush",
    price: 19.99,
    compareAtPrice: 27.99,
    description: "Professional deshedding brush with stainless steel blade. Reaches through topcoat to gently remove loose undercoat hair. Reduces shedding up to 90%. Self-cleaning — push button to eject hair. Ergonomic non-slip handle. 10K+ monthly sales on Amazon.",
    category: "Grooming Tools",
    tags: ["dog", "cat", "deshedding", "grooming", "brush", "shedding"],
    images: [
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.7,
    reviewCount: 12345,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-008",
    name: "Dog Nail Grinder with LED Light",
    slug: "dog-nail-grinder-with-led-light",
    price: 24.99,
    compareAtPrice: 34.99,
    description: "Quiet electric nail grinder with 2-speed motor and LED light. Safely files nails without splitting or cracking. Includes 3 grinding ports for small/medium/large pets. Built-in safety guard prevents over-grinding. Rechargeable — 6 hours of use.",
    category: "Grooming Tools",
    tags: ["dog", "cat", "nail", "grinder", "grooming", "LED"],
    images: [
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.5,
    reviewCount: 7890,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-009",
    name: "LED USB Rechargeable Dog Collar",
    slug: "led-usb-rechargeable-dog-collar",
    price: 18.99,
    compareAtPrice: 24.99,
    description: "Bright LED dog collar with 3 lighting modes (steady, slow flash, fast flash). USB rechargeable — 8-12 hours battery life. Waterproof silicone tube. Visible up to 1,500 ft. Perfect for night walks and camping. Sizes S-XL. Up to 80% profit margin.",
    category: "Collars & Leashes",
    tags: ["dog", "cat", "LED", "collar", "night", "safety", "rechargeable"],
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.4,
    reviewCount: 5678,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-010",
    name: "Interactive Cat Feather Toy",
    slug: "interactive-cat-feather-toy",
    price: 12.99,
    description: "Automatic feather toy that mimics bird movements. Motion-activated — starts when your cat approaches. 3 speed settings. Replaceable feather attachments. USB rechargeable battery. Keeps your cat entertained for hours. 7K+ monthly sales.",
    category: "Toys",
    tags: ["cat", "toy", "interactive", "feather", "automatic"],
    images: [
      "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80",
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80",
    ],
    rating: 4.6,
    reviewCount: 3456,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-011",
    name: "Dog Snuffle Mat",
    slug: "dog-snuffle-mat",
    price: 22.99,
    compareAtPrice: 29.99,
    description: "Interactive snuffle mat that mimics grass for natural foraging. Hide treats in the fleece strips — engages your dog's sense of smell. Slows down eating, reduces boredom, and provides mental stimulation. Hand washable. Non-slip rubber base. 10K+ sales.",
    category: "Toys",
    tags: ["dog", "snuffle mat", "foraging", "enrichment", "slow feeding", "mental stimulation"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    rating: 4.8,
    reviewCount: 7890,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-012",
    name: "Cat Water Fountain with Filter",
    slug: "cat-water-fountain-with-filter",
    price: 34.99,
    compareAtPrice: 49.99,
    description: "Stainless steel cat water fountain with triple filtration system. 2L capacity. Ultra-quiet pump. Flowing water encourages cats to drink more — prevents urinary tract issues. Replaceable carbon filters (recurring revenue). Dishwasher safe. 10K+ monthly sales.",
    category: "Feeding",
    tags: ["cat", "water", "fountain", "filter", "hydration", "stainless steel"],
    images: [
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80",
      "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80",
    ],
    rating: 4.5,
    reviewCount: 4321,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-013",
    name: "Dog Cooling Mat (Self-Cooling Gel)",
    slug: "dog-cooling-mat-self-cooling-gel",
    price: 29.99,
    compareAtPrice: 39.99,
    description: "Pressure-activated cooling mat — no water, electricity, or refrigeration needed. Filled with non-toxic cooling gel. Stays cool for 6-8 hours. Perfect for hot summer days, travel, and outdoor use. Durable Oxford fabric with non-slip bottom. Supports up to 100 lbs.",
    category: "Beds & Furniture",
    tags: ["dog", "cat", "cooling", "mat", "summer", "gel", "travel"],
    images: [
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
    ],
    rating: 4.4,
    reviewCount: 6543,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-014",
    name: "Indestructible Dog Chew Toy",
    slug: "indestructible-dog-chew-toy",
    price: 16.99,
    compareAtPrice: 22.99,
    description: "Made from natural rubber — built for aggressive chewers. Unique shape bounces unpredictably for exciting play. Treat-dispensing design. Floats in water. Non-toxic, FDA-approved materials. Satisfaction guaranteed — if your dog destroys it, we replace it free.",
    category: "Toys",
    tags: ["dog", "chew", "toy", "indestructible", "durable", "rubber"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    rating: 4.6,
    reviewCount: 9876,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-015",
    name: "Automatic Pet Feeder with Timer",
    slug: "automatic-pet-feeder-with-timer",
    price: 49.99,
    compareAtPrice: 69.99,
    description: "Programmable automatic feeder with digital timer. Dispenses up to 4 meals per day with precise portion control. Voice recording feature lets you call your pet at mealtime. Battery backup keeps schedule during power outages. 5L capacity. Easy-clean removable bowl.",
    category: "Feeding",
    tags: ["dog", "cat", "feeder", "automatic", "timer", "smart"],
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    rating: 4.5,
    reviewCount: 3456,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-016",
    name: "Biodegradable Dog Poop Bags (120-Pack)",
    slug: "biodegradable-dog-poop-bags-120-pack",
    price: 11.99,
    compareAtPrice: 15.99,
    description: "Eco-friendly, extra-thick poop bags made from plant-based materials. 100% biodegradable and compostable. Leak-proof with reinforced seams. Includes roll with dispenser and clip. 120 bags per pack. Perfect for subscription model — customers repurchase monthly.",
    category: "Health & Safety",
    tags: ["dog", "poop bags", "biodegradable", "eco-friendly", "waste"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
    ],
    rating: 4.7,
    reviewCount: 12345,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-017",
    name: "Collapsible Travel Dog Bowl",
    slug: "collapsible-travel-dog-bowl",
    price: 9.99,
    compareAtPrice: 14.99,
    description: "Silicone collapsible bowl that folds flat for travel. 2-cup capacity. Carabiner clip attaches to leash or bag. BPA-free, food-grade silicone. Available in 6 colors. Lightweight and dishwasher safe. Over 293 sales/month proven. Perfect add-on upsell item.",
    category: "Travel & Outdoors",
    tags: ["dog", "cat", "travel", "bowl", "collapsible", "silicone", "portable"],
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.8,
    reviewCount: 15678,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-018",
    name: "Motion-Activated Dog Ball Toy",
    slug: "motion-activated-dog-ball-toy",
    price: 29.99,
    compareAtPrice: 39.99,
    description: "Smart ball that activates on its own when it senses movement. Rolls, wobbles, and shakes to engage your dog. Durable ABS shell with soft silicone exterior. USB rechargeable — 4 hours of play. Interactive mode for 2-player fetch. 7K+ monthly sales.",
    category: "Toys",
    tags: ["dog", "smart", "ball", "motion-activated", "interactive", "toy"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    rating: 4.3,
    reviewCount: 2345,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-019",
    name: "Dog Raincoat with Reflective Strips",
    slug: "dog-raincoat-with-reflective-strips",
    price: 27.99,
    compareAtPrice: 36.99,
    description: "Waterproof dog raincoat with hood and leg straps. High-visibility reflective strips for night safety. Breathable polyester fabric with waterproof coating. Leash access hole on back. Elastic leg openings. Packs into included carrying bag. Sizes XS-XXL.",
    category: "Apparel",
    tags: ["dog", "raincoat", "waterproof", "reflective", "apparel", "outdoor"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
    ],
    rating: 4.4,
    reviewCount: 3456,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-020",
    name: "Paw Cleaner Cup",
    slug: "paw-cleaner-cup",
    price: 19.99,
    compareAtPrice: 24.99,
    description: "Portable paw cleaner with silicone bristles and water chamber. Insert paw and twist — mud and dirt rinse away. Fits all paw sizes. No more muddy paw prints in the house! Includes microfiber drying towel. Lightweight for travel. Trending on TikTok.",
    category: "Grooming Tools",
    tags: ["dog", "paw", "cleaner", "mud", "grooming", "travel"],
    images: [
      "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.5,
    reviewCount: 5678,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-021",
    name: "Cat Window Perch with Suction Cups",
    slug: "cat-window-perch-suction-cups",
    price: 29.99,
    description: "Sturdy window perch with heavy-duty suction cups. Supports up to 30 lbs. Removable fleece pad for comfort. 180° swivel rotation. Easy to install on any smooth surface. Gives your cat a front-row view of birds and outdoor action.",
    category: "Beds & Furniture",
    tags: ["cat", "perch", "window", "suction", "lounge", "furniture"],
    images: [
      "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80",
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80",
    ],
    rating: 4.3,
    reviewCount: 4567,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-022",
    name: "Pet First Aid Kit (60 Pieces)",
    slug: "pet-first-aid-kit-60-pieces",
    price: 24.99,
    compareAtPrice: 34.99,
    description: "Complete emergency kit with 60 essential items for your pet. Includes bandages, antiseptic wipes, tweezers, emergency blanket, scissors, instant cold pack, and pet-specific first aid guide. Compact rip-stop nylon case. Peace of mind for every pet parent.",
    category: "Health & Safety",
    tags: ["dog", "cat", "first aid", "emergency", "safety", "kit"],
    images: [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
    ],
    rating: 4.8,
    reviewCount: 2345,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-023",
    name: "Wall-Mounted Cat Scratcher",
    slug: "wall-mounted-cat-scratcher",
    price: 24.79,
    compareAtPrice: 32.99,
    description: "Sleek wall-mounted scratching pad that saves floor space. Natural sisal rope — irresistible to cats. Includes mounting kit. Replaceable sisal panels. Modern design complements any decor. Protects your furniture from claw marks. 10K+ monthly sales.",
    category: "Beds & Furniture",
    tags: ["cat", "scratcher", "wall-mounted", "sisal", "furniture"],
    images: [
      "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80",
      "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80",
    ],
    rating: 4.6,
    reviewCount: 8901,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-024",
    name: "Retractable Dog Leash 16ft",
    slug: "retractable-dog-leash-16ft",
    price: 19.99,
    compareAtPrice: 26.99,
    description: "Smooth retractable leash with 16ft strong nylon tape. Ergonomic rubberized handle reduces hand strain. One-button brake and lock system. Reflective tape for night visibility. Tangle-free design. Suitable for dogs up to 50 lbs.",
    category: "Collars & Leashes",
    tags: ["dog", "leash", "retractable", "walking", "reflective"],
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
    ],
    rating: 4.3,
    reviewCount: 7890,
    inStock: true,
    featured: false,
  },
]

export const categories = [
  { name: "Grooming Tools", slug: "grooming-tools", image: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=400&q=80", count: 5 },
  { name: "Beds & Furniture", slug: "beds-furniture", image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80", count: 4 },
  { name: "Feeding", slug: "feeding", image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80", count: 3 },
  { name: "Toys", slug: "toys", image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&q=80", count: 4 },
  { name: "Collars & Leashes", slug: "collars-leashes", image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80", count: 3 },
  { name: "Health & Safety", slug: "health-safety", image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&q=80", count: 2 },
  { name: "Apparel", slug: "apparel", image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&q=80", count: 1 },
  { name: "Travel & Outdoors", slug: "travel-outdoors", image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80", count: 2 },
]

export function getAllProducts(): Product[] {
  return products
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const category = categories.find((c) => c.slug === categorySlug)
  if (!category) return []
  return products.filter((p) => p.category === category.name)
}

export function getRelatedProducts(product: Product): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, 4)
}
