export interface Product {
  id: string
  name: string
  slug: string
  price: number
  compareAtPrice?: number
  description: string
  category: string
  tags: string[]
  images: string[]
  rating: number
  reviewCount: number
  inStock: boolean
  featured: boolean
}

const products: Product[] = [
  {
    id: "pet-001",
    name: "Orthopedic Memory Foam Pet Bed",
    slug: "orthopedic-memory-foam-pet-bed",
    price: 59.99,
    compareAtPrice: 89.99,
    description: "Premium orthopedic memory foam bed designed for pets of all ages. Features a washable cover, non-slip bottom, and therapeutic foam that relieves joint pressure. Perfect for dogs and cats who need extra comfort.",
    category: "Beds & Furniture",
    tags: ["dog", "cat", "bed", "orthopedic", "memory foam"],
    images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80", "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80"],
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-002",
    name: "Adjustable No-Pull Dog Harness",
    slug: "adjustable-no-pull-dog-harness",
    price: 34.99,
    compareAtPrice: 44.99,
    description: "Ergonomic no-pull harness with padded chest plate and adjustable straps. Features reflective stitching for night walks, a sturdy handle for control, and quick-release buckles for easy on/off.",
    category: "Collars & Leashes",
    tags: ["dog", "harness", "walking", "no-pull"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.6,
    reviewCount: 189,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-003",
    name: "Interactive Feather Wand Cat Toy",
    slug: "interactive-feather-wand-cat-toy",
    price: 14.99,
    description: "Engaging feather wand toy that triggers your cat's natural hunting instincts. Features replaceable attachments, a comfortable grip handle, and a retractable string. Hours of interactive fun!",
    category: "Toys",
    tags: ["cat", "toy", "interactive", "feather"],
    images: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80"],
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-004",
    name: "Premium Stainless Steel Pet Bowls (Set of 2)",
    slug: "premium-stainless-steel-pet-bowls",
    price: 24.99,
    compareAtPrice: 34.99,
    description: "High-quality stainless steel bowls with non-slip silicone base. Dishwasher safe, rust-proof, and available in multiple sizes. Includes one food bowl and one water bowl.",
    category: "Feeding",
    tags: ["dog", "cat", "bowl", "feeding", "stainless"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-005",
    name: "Self-Cleaning Cat Litter Box",
    slug: "self-cleaning-cat-litter-box",
    price: 129.99,
    compareAtPrice: 169.99,
    description: "Automatic self-cleaning litter box with carbon filter system. Features a spacious interior, low-entry design for senior cats, and a waste drawer that lasts up to 2 weeks. Whisper-quiet operation.",
    category: "Litter & Accessories",
    tags: ["cat", "litter box", "self-cleaning", "automatic"],
    images: ["https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&q=80"],
    rating: 4.3,
    reviewCount: 78,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-006",
    name: "Durable Chew Toy Set for Dogs",
    slug: "durable-chew-toy-set-for-dogs",
    price: 19.99,
    description: "Set of 3 heavy-duty chew toys made from non-toxic natural rubber. Includes a bone, a ring, and a ball. Perfect for aggressive chewers. Helps clean teeth and reduce anxiety.",
    category: "Toys",
    tags: ["dog", "toy", "chew", "durable", "rubber"],
    images: ["https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80"],
    rating: 4.4,
    reviewCount: 445,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-007",
    name: "Cat Tree Tower with Scratching Posts",
    slug: "cat-tree-tower-scratching-posts",
    price: 89.99,
    compareAtPrice: 119.99,
    description: "Multi-level cat tree with natural sisal scratching posts, cozy perches, and a hideaway cubby. Features a dangling toy and climbing ramp. Assembly required. Supports up to 30 lbs.",
    category: "Beds & Furniture",
    tags: ["cat", "tree", "scratching", "tower", "furniture"],
    images: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80"],
    rating: 4.6,
    reviewCount: 267,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-008",
    name: "GPS Pet Tracker Collar",
    slug: "gps-pet-tracker-collar",
    price: 79.99,
    description: "Real-time GPS tracker that attaches to your pet's collar. Features activity monitoring, virtual fence alerts, and water-resistant design. Works with iOS and Android. No monthly subscription required.",
    category: "Collars & Leashes",
    tags: ["dog", "cat", "gps", "tracker", "collar", "safety"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.2,
    reviewCount: 134,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-009",
    name: "Pet Hair Remover Roller (Reusable)",
    slug: "pet-hair-remover-roller-reusable",
    price: 12.99,
    description: "Eco-friendly reusable lint roller that removes pet hair from furniture, clothing, and car upholstery. No adhesive sheets needed — just rinse and reuse. Ergonomic handle for comfortable grip.",
    category: "Grooming",
    tags: ["dog", "cat", "grooming", "hair", "cleanup"],
    images: ["https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80"],
    rating: 4.5,
    reviewCount: 890,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-010",
    name: "Heated Pet Bed for Winter",
    slug: "heated-pet-bed-winter",
    price: 49.99,
    compareAtPrice: 64.99,
    description: "Self-warming heated pet bed with dual-zone heating and auto shut-off. Features plush fleece cover, low-voltage operation, and machine-washable design. Provides gentle warmth for senior or arthritic pets.",
    category: "Beds & Furniture",
    tags: ["dog", "cat", "bed", "heated", "winter"],
    images: ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80"],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-011",
    name: "Retractable Dog Leash (16ft)",
    slug: "retractable-dog-leash-16ft",
    price: 22.99,
    compareAtPrice: 29.99,
    description: "Smooth retractable leash with ergonomic handle and 16ft strong nylon tape. Features one-button brake system, reflective tape, and tangle-free design. Suitable for dogs up to 50 lbs.",
    category: "Collars & Leashes",
    tags: ["dog", "leash", "retractable", "walking"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-012",
    name: "Natural Catnip Toy Variety Pack",
    slug: "natural-catnip-toy-variety-pack",
    price: 16.99,
    description: "Set of 5 organic catnip toys in fun shapes — fish, mouse, star, ball, and banana. Made from organic catnip and durable fabric. Certified organic and safe for all cat breeds.",
    category: "Toys",
    tags: ["cat", "toy", "catnip", "organic"],
    images: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80"],
    rating: 4.6,
    reviewCount: 723,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-013",
    name: "Elevated Dog Bed with Canopy",
    slug: "elevated-dog-bed-with-canopy",
    price: 69.99,
    compareAtPrice: 89.99,
    description: "Elevated cooling dog bed with removable canopy for sun protection. Breathable mesh fabric allows airflow on all sides. Ideal for outdoor use, camping, or hot summer days. Folds flat for storage.",
    category: "Beds & Furniture",
    tags: ["dog", "bed", "elevated", "cooling", "outdoor", "canopy"],
    images: ["https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80"],
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-014",
    name: "Professional Pet Grooming Kit",
    slug: "professional-pet-grooming-kit",
    price: 44.99,
    compareAtPrice: 59.99,
    description: "Complete 12-piece grooming kit including slicker brush, deshedding tool, comb, nail clippers, and more. Suitable for long and short-haired breeds. Comes with a storage case.",
    category: "Grooming",
    tags: ["dog", "cat", "grooming", "kit", "brush"],
    images: ["https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&q=80"],
    rating: 4.5,
    reviewCount: 345,
    inStock: true,
    featured: true,
  },
  {
    id: "pet-015",
    name: "Automatic Pet Feeder with Timer",
    slug: "automatic-pet-feeder-timer",
    price: 54.99,
    compareAtPrice: 69.99,
    description: "Programmable automatic pet feeder with digital timer. Dispenses up to 4 meals per day with portion control. Features voice recording, battery backup, and easy-clean removable bowl.",
    category: "Feeding",
    tags: ["dog", "cat", "feeder", "automatic", "timer"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.3,
    reviewCount: 212,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-016",
    name: "Pet First Aid Kit (60 Pieces)",
    slug: "pet-first-aid-kit-60-pieces",
    price: 29.99,
    description: "Comprehensive first aid kit for pets with 60 essential items. Includes bandages, antiseptic wipes, tweezers, emergency blanket, and a pet-specific first aid guide. Compact carrying case included.",
    category: "Health & Safety",
    tags: ["dog", "cat", "first aid", "safety", "emergency"],
    images: ["https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80"],
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-017",
    name: "Personalized Pet ID Tag",
    slug: "personalized-pet-id-tag",
    price: 9.99,
    description: "Engraved stainless steel ID tag with your pet's name and your phone number. Rust-proof, durable, and comes with a silent ring attachment. Available in multiple shapes and colors.",
    category: "Collars & Leashes",
    tags: ["dog", "cat", "id", "tag", "personalized"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.7,
    reviewCount: 1234,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-018",
    name: "Dog Raincoat with Hood",
    slug: "dog-raincoat-with-hood",
    price: 32.99,
    compareAtPrice: 39.99,
    description: "Waterproof dog raincoat with adjustable hood and reflective strips. Lightweight and breathable fabric with leash access hole. Available in multiple sizes and colors. Keeps your pup dry on rainy walks.",
    category: "Apparel",
    tags: ["dog", "raincoat", "apparel", "waterproof", "reflective"],
    images: ["https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80"],
    rating: 4.4,
    reviewCount: 234,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-019",
    name: "Flea and Tick Prevention Collar",
    slug: "flea-tick-prevention-collar",
    price: 38.99,
    compareAtPrice: 49.99,
    description: "Water-resistant flea and tick collar providing 8 months of continuous protection. Uses natural essential oils — no harsh chemicals. Adjustable fit for small to large pets. Starts working within 24 hours.",
    category: "Health & Safety",
    tags: ["dog", "cat", "flea", "tick", "collar", "prevention"],
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80"],
    rating: 4.1,
    reviewCount: 654,
    inStock: true,
    featured: false,
  },
  {
    id: "pet-020",
    name: "Cat Window Perch with Suction Cups",
    slug: "cat-window-perch-suction-cups",
    price: 29.99,
    description: "Strong suction cup window perch for cats to lounge and watch birds. Supports up to 25 lbs with reinforced stitching and removable fleece pad. Easy to install on any smooth surface.",
    category: "Beds & Furniture",
    tags: ["cat", "perch", "window", "suction", "lounge"],
    images: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&q=80"],
    rating: 4.3,
    reviewCount: 345,
    inStock: true,
    featured: false,
  },
]

export const categories = [
  { name: "Beds & Furniture", slug: "beds-furniture", image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80", count: 4 },
  { name: "Collars & Leashes", slug: "collars-leashes", image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80", count: 4 },
  { name: "Toys", slug: "toys", image: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=400&q=80", count: 3 },
  { name: "Grooming", slug: "grooming", image: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=400&q=80", count: 2 },
  { name: "Feeding", slug: "feeding", image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80", count: 2 },
  { name: "Health & Safety", slug: "health-safety", image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&q=80", count: 2 },
  { name: "Apparel", slug: "apparel", image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&q=80", count: 1 },
  { name: "Litter & Accessories", slug: "litter-accessories", image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&q=80", count: 1 },
]

export function getAllProducts(): Product[] {
  return products
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const category = categories.find((c) => c.slug === categorySlug)
  if (!category) return []
  return products.filter((p) => p.category === category.name)
}

export function getRelatedProducts(product: Product): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, 4)
}
